'use strict';
(()=>{
const $=id=>document.getElementById(id), money=v=>v===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v), V=AirPulseVault;
let vault=window.AIRPULSE_ENCRYPTED_VAULT,book=null,password='',dirty=false,editingId=null,lastActivity=Date.now(),busy=false;
delete window.AIRPULSE_ENCRYPTED_VAULT;
function notify(message,isDirty=dirty){$('save-status').textContent=message;$('save-status').classList.toggle('dirty',isDirty);}
function changed(){dirty=true;notify('Unsaved changes. Save an encrypted file before closing or refreshing.');}
function categories(){return [...new Set(book.items.map(i=>i.category))].sort();}
function fillCategories(){const selected=$('category').value;$('category').replaceChildren(new Option('All categories','all'));$('category-list').replaceChildren();categories().forEach(c=>{$('category').add(new Option(c,c));$('category-list').append(new Option(c,c))});$('category').value=categories().includes(selected)?selected:'all';}
function stats(){const ready=book.items.filter(i=>V.sell(i.cost,i.labor,book.markup)!==null).length;$('total-items').textContent=book.items.length;$('ready-items').textContent=ready;$('missing-items').textContent=book.items.length-ready;$('markup').value=book.markup;$('formula-text').textContent=`Selling price = total direct cost × ${(1+book.markup/100).toFixed(3).replace(/0+$/,'').replace(/\.$/,'')}`;$('margin-text').textContent=`${book.markup}% markup is ${(book.markup/(100+book.markup)*100).toFixed(2)}% gross margin.`;calculate();}
function element(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function render(){if(!book)return;const query=$('search').value.trim().toLowerCase(),category=$('category').value,status=$('status').value;const filtered=book.items.filter(i=>{const ready=V.sell(i.cost,i.labor,book.markup)!==null;return(category==='all'||i.category===category)&&(status==='all'||(status==='ready'?ready:!ready))&&`${i.name} ${i.notes} ${i.category}`.toLowerCase().includes(query)});$('rows').replaceChildren();for(const item of filtered){const tr=document.createElement('tr'),name=document.createElement('td');name.append(element('span',item.name,'item-title'),element('span',`${item.scope} · ${item.unit}`,'item-scope'));const categoryCell=document.createElement('td');categoryCell.append(element('span',item.category,'category-tag'));const cost=element('td',money(item.cost)),labor=element('td',money(item.labor)),price=document.createElement('td'),value=V.sell(item.cost,item.labor,book.markup);price.append(element('span',value===null?'Cost needed':money(value),value===null?'needs-cost':'price'));const action=document.createElement('td'),button=element('button','Edit','edit-button');button.type='button';button.setAttribute('aria-label',`Edit ${item.name}`);button.addEventListener('click',()=>edit(item.id));action.append(button);tr.append(name,categoryCell,cost,labor,price,action);$('rows').append(tr);}$('result-count').textContent=`${filtered.length} of ${book.items.length} items`;$('empty').hidden=filtered.length!==0;}
function refresh(){fillCategories();stats();render();}
async function unlock(event){event.preventDefault();if(busy)return;$('unlock-error').textContent='';if(!crypto.subtle){$('unlock-error').textContent='Use HTTPS hosting or open this package locally in a modern browser.';return;}busy=true;$('unlock-button').disabled=true;$('unlock-button').textContent='Unlocking…';try{const entered=$('password').value;book=await V.decrypt(vault,entered);password=entered;$('password').value='';$('locked').hidden=true;$('workspace').hidden=false;lastActivity=Date.now();refresh();notify(dirty?'Recovered in-session edits. Save an encrypted file to keep them.':'Edits stay in this session until you save an encrypted file.');$('search').focus();}catch(error){book=null;password='';$('unlock-error').textContent='Could not unlock. Check the password and that you selected the correct vault file.';}finally{busy=false;$('unlock-button').disabled=false;$('unlock-button').textContent='Unlock price book';}}
$('unlock-form').addEventListener('submit',unlock);
$('locked-import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>12000000)throw new Error();const candidate=V.parseFile(await file.text());if(candidate.version!==1||!candidate.ciphertext)throw new Error();vault=candidate;dirty=false;$('unlock-error').textContent='Vault file loaded. Enter its password to unlock.';$('password').focus();}catch{$('unlock-error').textContent='That file is not a supported AirPulse encrypted vault.';}finally{event.target.value='';}});
async function lock(){if(!book||busy)return;busy=true;try{vault=await V.encrypt(book,password);book=null;password='';editingId=null;$('rows').replaceChildren();$('edit-form').reset();$('edit-price').textContent='—';$('edit-dialog').close();$('password-dialog').close();$('password-form').reset();$('search').value='';$('category').replaceChildren(new Option('All categories','all'));$('category-list').replaceChildren();for(const id of ['total-items','ready-items','missing-items','result-count','calc-total','calc-profit','formula-text','margin-text','save-status'])$(id).textContent='';for(const id of ['calc-material','calc-labor'])$(id).value='';$('workspace').hidden=true;$('locked').hidden=false;$('unlock-error').textContent=dirty?'Locked. Your in-session edits are encrypted; unlock and save before closing.':'';$('password').focus();}catch{notify('Unable to lock safely. Save an encrypted file, then close this tab.',true);}finally{busy=false;}}
$('lock').addEventListener('click',lock);
function download(envelope){const content='window.AIRPULSE_ENCRYPTED_VAULT = '+JSON.stringify(envelope)+';\n',blob=new Blob([content],{type:'text/javascript'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vault.js';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function save(){if(!book||busy)return;busy=true;$('download-vault').disabled=true;try{vault=await V.encrypt(book,password);download(vault);dirty=false;notify('Encrypted download prepared. Keep that file; replace the hosted vault.js to update the website.',false);}catch{notify('Could not save. Your edits are still here; try again.',true);}finally{busy=false;$('download-vault').disabled=false;}}
$('download-vault').addEventListener('click',save);
for(const id of ['search','category','status'])$(id).addEventListener(id==='search'?'input':'change',render);
$('markup').addEventListener('change',()=>{const n=Number($('markup').value);if($('markup').value===''||!Number.isFinite(n)||n<0||n>1000){$('markup').value=book.markup;return;}book.markup=n;changed();stats();render();});
function numeric(id){const value=$(id).value.trim();return value===''?null:Number(value);}
function calculate(){if(!book)return;const material=numeric('calc-material'),labor=numeric('calc-labor'),value=V.sell(material,labor,book.markup);$('calc-total').textContent=money(value);$('calc-profit').textContent=value===null?'Enter both costs; use 0 when a cost does not apply.':`Direct cost: ${money(material+labor)} · Gross profit before overhead and tax: ${money(value-material-labor)}`;}
for(const id of ['calc-material','calc-labor'])$(id).addEventListener('input',calculate);
function edit(id){editingId=id;const item=book.items.find(i=>i.id===id);$('edit-form').reset();$('edit-error').textContent='';$('edit-title').textContent=item?'Edit item':'Add catalog item';$('delete-item').hidden=!item;const defaults={name:'',category:$('category').value==='all'?'Other':$('category').value,unit:'Each',scope:'Parts only',cost:null,labor:0,notes:''};for(const key of ['name','category','unit','scope','cost','labor','notes'])$('item-'+key).value=(item||defaults)[key]??'';preview();$('edit-dialog').showModal();$('item-name').focus();}
function preview(){$('edit-price').textContent=money(V.sell(numeric('item-cost'),numeric('item-labor'),book.markup));}
for(const id of ['item-cost','item-labor'])$(id).addEventListener('input',preview);
$('add-item').addEventListener('click',()=>edit(null));$('close-edit').addEventListener('click',()=>$('edit-dialog').close());
$('edit-form').addEventListener('submit',event=>{event.preventDefault();const item={id:editingId||crypto.randomUUID(),name:$('item-name').value.trim(),category:$('item-category').value.trim(),unit:$('item-unit').value.trim(),scope:$('item-scope').value,cost:numeric('item-cost'),labor:numeric('item-labor'),notes:$('item-notes').value.trim()};try{const next={...book,items:editingId?book.items.map(i=>i.id===editingId?item:i):[...book.items,item]};V.validate(next);book=next;changed();refresh();$('edit-dialog').close();}catch{$('edit-error').textContent='Check the name, category, and costs. Costs must be blank or nonnegative numbers.';}});
$('delete-item').addEventListener('click',()=>{const item=book.items.find(i=>i.id===editingId);if(item&&confirm(`Delete “${item.name}” from this price book?`)){book.items=book.items.filter(i=>i.id!==editingId);changed();refresh();$('edit-dialog').close();}});
$('change-password').addEventListener('click',()=>{$('password-form').reset();$('password-error').textContent='';$('password-dialog').showModal();});$('close-password').addEventListener('click',()=>$('password-dialog').close());
$('password-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const next=$('new-password').value;if(next!==$('repeat-password').value){$('password-error').textContent='The passwords do not match.';return;}busy=true;try{const nextVault=await V.encrypt(book,next);password=next;vault=nextVault;download(vault);dirty=false;$('password-form').reset();$('password-dialog').close();notify('New encrypted file downloaded. Replace hosted vault.js; older copies still use the old password.',false);}catch{$('password-error').textContent='Could not change the password. Please try again.';}finally{busy=false;}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
for(const type of ['pointerdown','keydown','input','scroll'])document.addEventListener(type,()=>lastActivity=Date.now(),{passive:true});setInterval(()=>{if(book&&Date.now()-lastActivity>600000)void lock();},15000);
})();
