'use strict';
// The password and plaintext catalog never leave this browser.
// Only the AES-GCM encrypted envelope is included in downloadable vault.js files.
(function(root){
 const ITERATIONS=600000, enc=new TextEncoder(),dec=new TextDecoder();
 const b64=b=>{const bytes=new Uint8Array(b);let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);};
 const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 async function derive(password,salt){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
 function validate(data){if(!data||data.version!==1||!Number.isFinite(data.markup)||data.markup<0||data.markup>1000||!Array.isArray(data.items)||data.items.length>10000)throw new Error('Invalid price book.');const ids=new Set();for(const i of data.items){if(!i||typeof i.id!=='string'||ids.has(i.id)||typeof i.name!=='string'||!i.name.trim()||i.name.length>180||typeof i.category!=='string'||!i.category.trim()||i.category.length>70||typeof i.unit!=='string'||i.unit.length>40||!['Parts only','Installed / complete job','Service / labor','Materials only'].includes(i.scope)||typeof i.notes!=='string'||i.notes.length>2000)throw new Error('Invalid catalog item.');ids.add(i.id);for(const n of ['cost','labor']){if(i[n]!==null&&(!Number.isFinite(i[n])||i[n]<0||i[n]>10000000))throw new Error('Invalid item cost.');}}return data;}
 function sell(cost,labor,markup){if(cost===null||labor===null||![cost,labor,markup].every(Number.isFinite)||cost<0||labor<0||markup<0)return null;return Math.round(((cost+labor)*(1+markup/100)+Number.EPSILON)*100)/100;}
 async function encrypt(data,password){validate(data);if(typeof password!=='string'||password.length<16)throw new Error('Use at least 16 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const key=await derive(password,salt);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('AirPulseVault:v1')},key,enc.encode(JSON.stringify(data)));return {version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:b64(salt),iv:b64(iv),ciphertext:b64(ciphertext)};}
 async function decrypt(vault,password){if(!vault||vault.version!==1||vault.algorithm!=='AES-256-GCM'||vault.kdf!=='PBKDF2-SHA256'||vault.iterations!==ITERATIONS||typeof vault.ciphertext!=='string'||vault.ciphertext.length>10000000)throw new Error('Unsupported encrypted file.');const salt=unb64(vault.salt),iv=unb64(vault.iv);if(salt.length!==16||iv.length!==12)throw new Error('Invalid encryption envelope.');const key=await derive(password,salt);const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode('AirPulseVault:v1')},key,unb64(vault.ciphertext));return validate(JSON.parse(dec.decode(plaintext)));}
 function parseFile(text){const prefix='window.AIRPULSE_ENCRYPTED_VAULT = ';let body=text.trim();if(body.startsWith(prefix))body=body.slice(prefix.length).replace(/;\s*$/,'');return JSON.parse(body);}
 root.AirPulseVault={encrypt,decrypt,validate,sell,parseFile};
})(globalThis);
